{% set name = "kwallet" %}
{% set version = "5.72.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kwallet-{{ version }}.tar.xz
  sha256: 3a1624ae9bd8384ca981b38cdf026abb31a6708e5f12680cd71605316cdf4c9f

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kwallet', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - gpgme
    - libgcrypt
    - ki18n >={{ version }}
    - kconfig >={{ version }}
    - kservice >={{ version }}
    - kcoreaddons >={{ version }}
    - kdbusaddons >={{ version }}
    - kwindowsystem >={{ version }}
    - kconfigwidgets >={{ version }}
    - knotifications >={{ version }}
    - kwidgetsaddons >={{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Wallet.so

about:
  home: https://api.kde.org/frameworks/kwallet/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Safe desktop-wide storage for passwords
  dev_url: https://cgit.kde.org/kwallet.git/tree

extra:
  recipe-maintainers:
    - scopatz
