{% set name = "kwallet" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kwallet-{{ version }}.tar.xz
  sha256: 7abcf5230c7112628d4b1ac37648ab2d7fb147e4fda61e7aa0fd0da1d59cb0a1

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kwallet', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ major_minor }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - qt
    - gpgme
    - libgcrypt
    - ki18n >={{ major_minor }}
    - kconfig >={{ major_minor }}
    - kservice >={{ major_minor }}
    - kcoreaddons >={{ major_minor }}
    - kdbusaddons >={{ major_minor }}
    - kwindowsystem >={{ major_minor }}
    - kconfigwidgets >={{ major_minor }}
    - knotifications >={{ major_minor }}
    - kwidgetsaddons >={{ major_minor }}

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Wallet.so

about:
  home: https://api.kde.org/frameworks/kwallet/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Safe desktop-wide storage for passwords
  dev_url: https://cgit.kde.org/kwallet.git/tree

extra:
  recipe-maintainers:
    - scopatz
