travis:
  secure:
    BINSTAR_TOKEN: ByKzqw0VALxBzq2ZE7GDHQ+U/tBvmCkxFhu40NVLQ4GQibayPVqwy1ie074aKHmQAHfkjTKb31QbRS4ejUlivR8ec3KcNBbqLEMktsyYZJxEg0yH5E22IQk8OEfzwotpm3E2rGxPFx+OzZ8xCvEv0/4nRr8BW6k3b8fiU465w5VHRUlyvulFXkNszPyGP06RX4dVIV88XuDHmTxtLm6GcpjOUBTl4Gx/VuVE1nuRvflrbJfrWPfgHggGdtf3FAty6fPEdusqsShnzBelwAYjIxDapPZvBWar0YsOw/2CAcCujvmQAWiyj9ZK7eXzXqlQu1tiBQ1He78J1XxvYzf0EhsiW2KhVwmlY6ncymNgYDJ5mtT/2yH0pwXmJoGcCHzhh0es6TIUSHT2L3nV6O9+BWT9NAxcV6s2Vs8rOwo0Gj2jotEBN3bq2kts0RuB3LhP1QgTzvO7JqOGlxLSbmKmzm8TinKcB+OrjpYQvvHIyN9SNhS6fZM6uYIDtIxX5qdqcByDLo9xL0nbeBJe2zSsRyxAGoZTNG9MJWLrpjK1pW5fJpcLdTfStYZB+5wxRL4ddwXOXO/wATLUQQtx0fFJ4LNTuB4lgjmVXPJ3o717WmeaT70XpD5h44pkdWAHOdF0HAjR2t/5CWsBLwVb9hfX8n0vflI9PLRmgZkUI5DbPYQ=
conda_forge_output_validation: true
bot:
  check_solvable: True
  
